version: '3'

services:
  streamlit:
    build: 
        context: .
        dockerfile: streamlit\Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - api

  api:
    build:
        context: .
        dockerfile: api\Dockerfile
    ports:
      - 8001:8001
