version: '3'

services:
  streamlit:
    build: 
        context: .
        dockerfile: streamlit\Dockerfile
    ports:
      - 8505:8505
    depends_on:
      - api

  api:
    build:
        context: .
        dockerfile: api\Dockerfile
    ports:
      - 8005:8005
